basePath: /
host: localhost:8080
info:
  contact: {}
  description: Contoh REST API menggunakan Go + Swagger
  title: Example API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Mengembalikan pesan sapaan
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Menyapa pengguna
      tags:
      - contoh
swagger: "2.0"
